language: node_js
node_js:
  - "node"
before_script:
  - npm install -g mocha
script:
  - npm test
  - WATSON_API_URL=$WatsonApiUrl npm run build
  - cd ./dist && zip -r ./Watson.Plugins.Chrome_$TRAVIS_TAG.zip . && cd ..
deploy:
  provider: releases
  api_key: "$GithubOAuth"
  file: ./dist/Watson.Plugins.Chrome_$TRAVIS_TAG.zip
  skip_cleanup: true  
  on:
    tags: true